name: Auto-merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    name: Enable auto-merge (Dependabot)
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      github.event.pull_request.draft == false &&
      github.event.pull_request.base.ref == 'main'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@25dd0e34f4fe68f24cc83900b1fe3fe149efef98 #v3.1.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Enable auto-merge for patch and minor updates
        if: |
          contains(steps.metadata.outputs.update-type, 'semver-patch') ||
          contains(steps.metadata.outputs.update-type, 'semver-minor')
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  owner:
    name: Enable auto-merge (owner)
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.user.login == 'hrdtbs' &&
      github.event.pull_request.draft == false &&
      github.event.pull_request.base.ref == 'main'
    steps:
      - name: Enable auto-merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
